import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script"; // اضافه کردن کامپوننت Script
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* بارگذاری اسکریپت‌ها به صورت ناهمزمان */}
        <Script src="/libs/gumshoejs/gumshoe.polyfills.min.js" strategy="lazyOnload" />
        <Script src="/libs/tobii/js/tobii.min.js" strategy="lazyOnload" />
        <Script src="/libs/tiny-slider/min/tiny-slider.js" strategy="lazyOnload" />
        <Script src="/libs/feather-icons/feather.min.js" strategy="lazyOnload" />
        <Script src="/js/plugins.init.js" strategy="lazyOnload" />
        <Script src="/js/app.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}